# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'MVVMC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMC
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  target 'MVVMCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
